language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - pypy

sudo: false

script:
  - TOX_COMMAND="tox -e py`echo "$TRAVIS_PYTHON_VERSION"|sed "s/\.//"`"
  - echo "Running: $TOX_COMMAND"
  - `$TOX_COMMAND`

install:
  - pip install --upgrade tox
  
after_failure:
  - for X in .tox/$TOX_ENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
  - echo "pip.log\n"; cat $HOME/.pip/pip.log

notifications:
  irc:
    channels: "irc.freenode.org#invirtualenv"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false
