language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - pypy

sudo: false

script:
  - TOX_ENV_NAME="py`echo "$TRAVIS_PYTHON_VERSION"|sed "s/\.//"`"
  - tox -v -v -e $TOX_ENV_NAME

install:
  - pip install --upgrade pip setuptools detox coveralls virtualenv

after_success:
  coveralls
  
after_failure:
  - for X in .tox/$TOX_ENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
  - echo "pip.log\n"; cat $HOME/.pip/pip.log

notifications:
  irc:
    channels: "irc.freenode.org#invirtualenv"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false
